#Lijst met keywords

Keywords = ['LOX-1'         ,
            'LOX-5'         ,
            'LOX-9'         ,
            'LOX-12'        ,
            'LOX-13'        ,
            'PLASTIC'       ,
            'HORMONE'       ,
            'GLUE'          ,
            'FLAVORING'     ,
            'AGENTS'        ,
            'REGULATE'      ,
            'INHIBITION'    ,
            'OXIDATION'     ,
            'LYPOXYGENASE'  ,
            'EXPRESSION'    ,
            'MEDICINE'      ,
            'ACITVITY'      ,
            'PROTEIN'       ,
            'RECOMBINATION' ,
			'MEDICAL'		,
			'HUMAN'			,
			'PLANT'			,
			'RESEARCH'		,
			'BACTERIA'		,
			'ARCHAEA'		,
			'EUKARYOTA'		,
			'ANIMAL'		,
			'FUNGI'			,
			'CANCER'		,
			'TUMOR'			,
			'BIOLOGY'		,
			'INDUCED'		,
			
            ]
            
            
